server:
  port: 13001

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://1.94.170.182:3306/smartclassroom
    username: root
    password: root
  redis:
    host: 1.94.170.182
    port: 6379
    password: redis
  application:
    name: teacher-service
  cloud:
    nacos:
      server-addr: 1.94.170.182:12588
      username: nacos
      password: nacos
user-service:
  ribbon:
    NFLoadBalancingRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
mvc:
  static-path-pattern: /**