server:
  port: 13000

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://1.94.170.182:16033/smartclassroom?useAffectedRows=true
    username: byh
    password: byh2001..@
  redis:
    host: 1.94.170.182
    port: 19736
    password: byh2001..@
  cloud:
    nacos:
      server-addr: 1.94.170.182:12588
      username: nacos
      password: nacos

mvc:
  static-path-pattern: /**