server:
  port: 12000

spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:mysql://1.94.170.182:16033/smartclassroom?useAffectedRows=true
    username: byh
    password: byh2001..@
  redis:
    host: 1.94.170.182
    port: 19736
    password: byh2001..@
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 1.94.170.182:12588
      username: nacos
      password: nacos
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/video/**
      globalcors:
        add-to-simple-url-handler-mapping: true  # 确保配置生效于所有路由
        cors-configurations: # 注意属性名是 cors-configurations（小写）
          '[/**]': # 匹配所有路径
            allowedOrigins: "*"  # 允许所有源（注意：生产环境需指定具体域名）
            allowedMethods: "*"  # 允许所有HTTP方法
            allowedHeaders: "*"  # 允许所有请求头
            allowCredentials: true  # 允许携带凭证（如 Cookie）
            max-age: 36000  # 跨域策略缓存时间（单位：秒）