server:
  port: 13002

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://1.94.170.182:16033/smartclassroom?useAffectedRows=true
    username: byh
    password: byh2001..@
  redis:
    host: 1.94.170.182
    port: 19736
    password: byh2001..@
  application:
    name: video-service
  cloud:
    nacos:
      server-addr: 1.94.170.182:12588
  servlet:
    multipart:
      max-file-size: 6GB
      max-request-size: 6GB
user-service:
  ribbon:
    NFLoadBalancingRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

mvc:
  static-path-pattern: /**
