server:
  port: 13002

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartclassroom
    username: root
    password: root
  application:
    name: video-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
user-service:
  ribbon:
    NFLoadBalancingRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

mvc:
  static-path-pattern: /**
